### ISSUE TITLE
Role freezes waiting for signatures on rhel-like OSes.

### ISSUE THREAD

**Issue by mjourdan** [cisagov/ansible-role-clamav#62]
# 🐛 Summary #

While deploying, the role freezes on this step:

```
TASK [cisagov.clamav : Wait for new signatures to be downloaded and installed by freshclam] *********************************************************************************************************************
```

## To reproduce ##

1. Use a SELinux enabled host as your ansible target (I could reproduce it with Cent OS 7, RHEL 8)
2. Host a clamav private mirror on TCP port 8000 (as it is [the one cvdupdate uses by default](https://github.com/Cisco-Talos/cvdupdate))
3. Declare the configuration below in ansible:

```
clamav_freshclam_configuration:
  DatabaseMirror: ['db.local.clamav.net', 'database.clamav.net']
  Bytecode: 'true'
  PrivateMirror: "http://{{ clamav_private_mirror }}:8000"
  ScriptedUpdates: 'no'
  HTTPProxyServer:
  HTTPProxyPort:
  HTTPProxyUsername:
  HTTPProxyPassword:
```

## Expected behvior ##

Role deployment is successful.

## Any helpful log output or screenshots ##

While the role is stalled, running `systemctl status clamav-freshclam` on the host gives the following output:

```
déc. 05 14:22:47 test-centos systemd[1]: Started ClamAV virus database updater.
déc. 05 14:22:47 test-centos freshclam[18474]: ClamAV update process started at Mon Dec  5 14:22:47 2022
déc. 05 14:22:47 test-centos freshclam[18474]: WARNING: DNS Update Info disabled. Falling back to HTTP mode.
déc. 05 14:22:47 test-centos freshclam[18474]: Trying to retrieve CVD header from http://cvdupdate:8000/daily.cld
déc. 05 14:22:47 test-centos freshclam[18474]: WARNING: remote_cvdhead: Download failed (7) WARNING:  Message: Couldn't connect to server
déc. 05 14:22:47 test-centos freshclam[18474]: Trying to retrieve CVD header from http://cvdupdate:8000/daily.cvd
déc. 05 14:22:47 test-centos freshclam[18474]: WARNING: remote_cvdhead: Download failed (7) WARNING:  Message: Couldn't connect to server
déc. 05 14:22:47 test-centos freshclam[18474]: WARNING: Failed to get daily database version information from server: http://cvdupdate:8000
déc. 05 14:22:47 test-centos freshclam[18474]: ERROR: check_for_new_database_version: Failed to find daily database using server http://cvdupdate:8000.
déc. 05 14:22:47 test-centos freshclam[18474]: Trying again in 5 secs...
```

Audit logs show the following:

```
type=AVC msg=audit(1671773505.429:258326): avc:  denied  { name_connect } for  pid=1068 comm="freshclam" dest=8000 scontext=system_u:system_r:antivirus_t:s0 tcontext=system_u:object_r:soundd_port_t:s0 tclass=tcp_socket permissive=1
type=SYSCALL msg=audit(1671773505.429:258326): arch=c000003e syscall=42 success=no exit=-115 a0=5 a1=7fff36ad6fd0 a2=10 a3=2 items=0 ppid=1 pid=1068 auid=4294967295 uid=992 gid=990 euid=992 suid=992 fsuid=992 egid=990 sgid=990 fsgid=990 tty=(none) ses=4294967295 comm="freshclam" exe="/usr/bin/freshclam" subj=system_u:system_r:antivirus_t:s0 key=(null)
```

Opening a shell on the host to manually run the `freshclam` command as root allows to work around.

**Comment by mcdonnnj** [comment]
Per https://github.com/cisagov/ansible-role-clamav/pull/63#issuecomment-1430459378:
> I spent a lot of time thinking about how to make the SELinux policy changes that you are adding in a clean way that passes `ansible-lint`. After that I started to wonder why this change is necessary in the first place.
> 
> The problem is that [the SELinux policy for `freshclam`](https://github.com/fedora-selinux/selinux-policy/blob/f37/policy/modules/contrib/clamav.te) is [only allowing the standard HTTP port](https://github.com/fedora-selinux/selinux-policy/blob/f37/policy/modules/contrib/clamav.te#L232-L234). You are trying to connect to a private mirror on port `8000`, which is in violation of this policy.
> 
> I think the answer here is to either
> 
>     * Make the changes to the SELinux policy that are required for your local environment (i.e., allow `freshclam` to reach out on port `8000`) _outside_ of this Ansible role
> 
>     * Or, have your local ClamAV mirror start listening on port `80`
> 
> 
> In any event, I don't think these changes belong in this Ansible role. This Ansible role is intended to install and configure ClamAV, but it cannot support generic tweaking of the SELinux policy for your local environment; such support belongs, perhaps, in a locale-specific Ansible role.
> 
> If you feel differently, feel free to fork this repo and create your own version of this Ansible tole.
